### PR TITLE
style changes

### PR DESCRIPTION
**Pull request by makurj**
https://github.com/uiowa/uiowa/issues/4064#issuecomment-912618925

### CODE REVIEW

**Comment by bspeare** [comment]
I think we want to set the grey text to a normal font weight:
```
.headline__text b {
    color: #737373;
    font-weight: normal;
}
```

**Comment by bspeare** [comment]
I think we want to crop this image: http://localhost:3000/images/viewbook/7.jpg to something like our Drupal image style: Ultrawide (1312 x 562).   And run any new images added through https://compressor.io/.

**Comment by bspeare** [comment]
Also, let's change this text out of uppercase to follow the style of all the stats on the page:

Screen Shot 2021-09-03 at 11 01 04 AM

**Comment by bspeare** [comment]
We could also look at optimizing the other images: https://webspeedtest.cloudinary.com/results/210903_AiDcGV_98ce8f132b9c706b7a9a00ea2288288f

**Comment by bspeare** [comment]
If they insist on using the nighttime shot for the first banner image, we could also dial down the gradient opacity so we can see the image: `background: linear-gradient(180deg, transparent 0, rgba(0, 0, 0, 0.37) 70%);`

**Comment by makurj** [comment]
Card text updated, header image cropped, other images run through compressor.io.

**Comment by makurj** [comment]
Night time header image updated. Pushing up now.

**Comment by bspeare** [comment]
Thanks for making the changes!  One more thing.  Can we set the default banner background to a solid opacity and then add in the gradient at the `sm` breakpoint?  That would help legibility for mobile:

Screen Shot 2021-09-03 at 11 40 27 AM

Screen Shot 2021-09-03 at 11 40 34 AM

**Comment by bspeare** [comment]
Screen Shot 2021-09-03 at 12 48 55 PM

Looks like we need to remove this card border for mobile as well.

**Review by bspeare — APPROVED** [review]
Thanks for making the changes!

**Comment by richardbporter** [comment]
Should this have been merged into main?

**Comment by makurj** [comment]
Once we have final confirmation from Jess and Laura.

**Comment by makurj** [comment]
From Jess:
We have just a few edits before we send to Laura for review.

> There are two minor typos in the “Learn from expert legal scholars section” (attached)
> “U.S News & World Report” and “National Jurist” in the stats bar should be italicized.
> In the second stats bar, can we remove the hover  effect and bring all the text to the front by default. It's broken a bit oddly as it is now.

[LawVB-R2Edits.pdf](https://github.com/uiowa/viewbook-law/files/7123163/LawVB-R2Edits.pdf)

**Comment by makurj** [comment]
More changes...
[LAW-Edits.pdf](https://github.com/uiowa/viewbook-law/files/7130739/LAW-Edits.pdf)

**Pull request merged**
